# Generated by Django 2.2.3 on 2021-09-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='lastname',
        ),
        migrations.AddField(
            model_name='user',
            name='firstname',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
